name: 'Continuous Delivery'

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.mle-shlomovolosky }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Configure Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.mle-shlomovolosky }}/challenge:${{ github.sha }} .
          docker push gcr.io/${{ secrets.mle-shlomovolosky }}/challenge:${{ github.sha }}
      
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy your-service-name \
            --image=gcr.io/${{ secrets.mle-shlomovolosky }}/challenge:${{ github.sha }} \
            --platform=managed \
            --region=us-central1  # Adjust this to your desired region
